### PR TITLE
Migrating applications assembly to gradle.

### PR DESCRIPTION
**Pull request by kidoz**
For the convenience of further development.

### CODE REVIEW

**Comment by contra** [comment]
Really nice! Thanks for this - have you tested this out and confirmed the JAR output is working fine?

**Comment by kidoz** [comment]
Yep!

Working on the new pull requests:
1) Decomposition of modules: core, cmd, gui (javafx)
2) Addition of testing with testng.

**Comment by contra** [comment]
@kidoz Interested in becoming a maintainer? I haven't touched java in years and this project has gone untouched since then

**Comment by kidoz** [comment]
Yes. A good project should continue to develop.

**Comment by contra** [comment]
@kidoz I added you to the repository, you should have access to commit now.

Core mission of the project:
- Reliabile
- Easy to use
- Deobfuscate as much as possible, no matter how painful
- Stay up to date with the latest versions of obfuscators

I created this project when I was 14 or 15 years old so I'm sure the code could use some serious cleaning.

**Comment by contra** [comment]
BTW if you're interested, around the same time I made this I also wrote an obfuscator (https://github.com/contra/jmot) which contains some newer code for deobfuscating allatori and jshrink (https://github.com/contra/JMOT/tree/master/src/net/contra/obfuscator/trans/deob)

**Comment by kidoz** [comment]
Thanks!

2016-01-13 8:59 GMT+03:00 contra <notifications@github.com>:

**Pull request merged**
